#!/usr/bin/env python
"""
Sets variables (custom or otherwise) of a session or subject in a MBI-XNAT
project

User credentials can be stored in a ~/.netrc file so that they don't need to be
entered each time a command is run. If a new user provided or netrc doesn't
exist the tool will ask whether to create a ~/.netrc file with the given
credentials.
"""
import argparse
import re
from xnatutils import varput, XnatUtilsUsageError, __version__

parser = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawTextHelpFormatter)
parser.add_argument('subject_or_session_id', type=str,
                    help="Name of subject or session to set the variable of")
parser.add_argument('variable', type=str,
                    help="Name of the variable to set")
parser.add_argument('value', help="Value of the variable")
parser.add_argument('--user', '-u', type=str, default=None,
                    help=("The user to connect to MBI-XNAT with"))
parser.add_argument('--version', '-V', action='version',
                    version='%(prog)s ' + __version__)
args = parser.parse_args()


try:
    varput(args.subject_or_session_id, args.variable, args.value,
           user=args.user)
except XnatUtilsUsageError as e:
    print(e)