#!/usr/bin/env python
"""
Gets the value of a variable (custom or otherwise) of a session or subject in a
MBI-XNAT project

User credentials can be stored in a ~/.netrc file so that they don't need to be
entered each time a command is run. If a new user provided or netrc doesn't
exist the tool will ask whether to create a ~/.netrc file with the given
credentials.
"""
from __future__ import print_function
import argparse
import logging
from xnatutils import (
    varget, __version__, print_response_error, print_usage_error)
from xnatutils.exceptions import XnatUtilsUsageError
from xnat.exceptions import XNATResponseError

logger = logging.getLogger('xnat-utils')
handler = logging.StreamHandler()
handler.setLevel(logging.INFO)
formatter = logging.Formatter("%(levelname)s - %(message)s")
handler.setFormatter(formatter)
logger.addHandler(handler)

parser = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawTextHelpFormatter)
parser.add_argument('subject_or_session_id', type=str,
                    help="Name of subject or session to get the variable from")
parser.add_argument('variable', type=str,
                    help="Name of the variable to get")
parser.add_argument('--default', type=str, default='',
                    help="Default value if object does not have a value")
parser.add_argument('--user', '-u', type=str, default=None,
                    help=("The user to connect to MBI-XNAT with"))
parser.add_argument('--version', '-V', action='version',
                    version='%(prog)s ' + __version__)
parser.add_argument('--server', '-s', type=str, default=None,
                    help="XNAT server to connect to")
args = parser.parse_args()

try:
    print(varget(args.subject_or_session_id, args.variable,
                 default=args.default, user=args.user,
                 server=args.server), end='')
except XnatUtilsUsageError as e:
    print_usage_error(e)
except XNATResponseError as e:
    print_response_error(e)
    